language: node_js
node_js:
  - '7'
script:
  - npm test
after_success:
  - npm run codecov
before_deploy:
  - cd dist
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  provider: npm
  skip_cleanup: true
  email: "laheen@gmail.com"
  api_key: $NPM_KEY
  on:
    tags: true
